cmake_minimum_required(VERSION 3.22.1)
project(bookocr LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(NCNN_VULKAN OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(NCNN_OPENMP ON CACHE BOOL "" FORCE)
set(NCNN_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../../../third_party/ncnn ${CMAKE_CURRENT_BINARY_DIR}/ncnn)
# Test builds must also have useful inference speed.
target_compile_options(ncnn PRIVATE $<$<CONFIG:Debug>:-O2>)
add_library(bookocr SHARED bookocr.cpp)
target_link_libraries(bookocr ncnn android jnigraphics log)
target_link_options(bookocr PRIVATE "-Wl,-z,max-page-size=16384")
